### ISSUE TITLE
如果完美支持openwrt就买这个型号了

### ISSUE THREAD

**Issue by wxg4net** [updateing/openwrt-r6220#1]

**Comment by updateing** [comment]
我在OpenWrt论坛发了帖子： https://forum.openwrt.org/viewtopic.php?id=59595 目前Flash被我玩坏掉了，等到修好才会接着移植。

**Comment by wxg4net** [comment]
辛苦。会持续关注这款路由器。
另外，这款路由器功耗怎么样？发热厉害么？有什么其它明显的缺点么？

**Comment by updateing** [comment]
因为没有长时间用，所以不能太早下结论。

**Comment by wxg4net** [comment]
看来一切都得等待去发现。求即时通讯联系方式

**Comment by updateing** [comment]
还是用邮箱吧，haotia at gmail.com

**Comment by updateing** [comment]
见 #4
