### ISSUE TITLE
r6220希望继续更新啊！nand flash 貌似可以换成spi 的flash 

### ISSUE THREAD

**Issue by jessons** [updateing/openwrt-r6220#3]
继续更新啊！都等着呢！
网件的3700 v5 和这个基本一样配置 pcb完全一样 flash不一样 https://forum.openwrt.org/viewtopic.php?id=56737

**Comment by updateing** [comment]
我看到那个改SPI Flash的帖了，然而还是没有时间做硬件方面的大改动……

**Comment by jessons** [comment]
问一下 为什么我的路由器tx 连上就没法开机 ，需要先按电源开机再插上tx 才能开机连上，还有你帖子里提到要rx 接个下拉电阻 ，tx这个还要下拉吗？下拉电阻1k可以吗？

**Comment by updateing** [comment]
把电阻换个到TX试试……阻值1K应该可以的。
TTL的改装不是我做的，是交给其他硬件比较强的人做的，所以我也不是很了解，抱歉。

**Comment by jessons** [comment]
能不能给个你测试的固件试试，我用你的编译不出来也不知道是我操作问题还是系统问题。vps 的debian系统。网件的官方固件最后两个分区看名字是保留分区 ，能不能格式化成ext4分区，官方固件能不能保存设置，或者修改那里的配置可以保存设置，通过串口连接进入系统的设置。

**Comment by updateing** [comment]
Flash坏了以后所有成品都删掉了……
我直接采用了不同的Flash分区表。后面一大块用于jffs了。

**Comment by updateing** [comment]
#2 #3 刚才尝试了改成SPI Flash，仍然无法启动。无限期搁置了……

**Comment by jessons** [comment]
可以去恩山看看刷个不死uboot会不会好

**Comment by updateing** [comment]
已经在SPI Flash中写好了newifi D1的Breed才装进路由的，然而并没有用。

**Comment by jessons** [comment]
哎！怎么这么不顺利

**Comment by jessons** [comment]
刷dir-860l  b2 的固件可以吗？也是spi的flash，配置一样http://downloads.openwrt.org/chaos_calmer/15.05/ramips/mt7621/  怎么没有人折腾这款路由器 价格配置不错啊！

**Comment by updateing** [comment]
我估计是硬件损坏的……

**Comment by jessons** [comment]
硬件毁了就不好办了

**Comment by jessons** [comment]
我想从nand上引出spi flash需要的8个线接flash,通过改电阻位置改spi启动，可不可以，两种闪存都接入会不会有影响？

**Comment by updateing** [comment]
对于硬件真的是不了解，还是得去问那个帖子的原作者……抱歉

**Comment by updateing** [comment]
见 #4
