### ISSUE TITLE
同求继续更新

### ISSUE THREAD

**Issue by mrLann** [updateing/openwrt-r6220#4]

**Comment by updateing** [comment]
设备已亡，应该是硬件损坏的……其实有编程器的话可以刷个MT7621的Breed接着玩的

**Comment by updateing** [comment]
https://github.com/updateing/lede-r6220-spi/tree/r6220-spi 改SPI后可用的LEDE在这里，可以尝试。
#3 #2 #1

**Comment by wwqgtxx** [comment]
@updateing "改SPI"要怎么弄？

**Comment by updateing** [comment]
硬件上把NAND Flash取下，改装成SPI Flash。搜一下有相关教程。

**Comment by wwqgtxx** [comment]
我勒个去，没有不改硬件的办法么。。。

**Comment by updateing** [comment]
抱歉，我没有使用NAND的R6220了。

On Thu, Oct 20, 2016 at 12:42 PM +0800, "wwqgtxx" notifications@github.com wrote:

我勒个去，没有不改硬件的办法么。。。

**Comment by wwqgtxx** [comment]
看来我的6220只能继续吃灰了，原厂固件实在是太不好用了
