### ISSUE TITLE
libiconv库

### ISSUE THREAD

**Issue by stelectronic** [updateing/openwrt-r6220#5]
openwrt的toolchain里没有libiconv的库, 请问怎么把libiconv的库加到toolchain里面去呢,

**Comment by updateing** [comment]
这个repo是OpenWrt的源码仓库，那么只需要在`make menuconfig`的Libraries中选择libiconv即可。

此外，相比把库添加到工具链中去，添加`CFLAGS`和`LIBS`或者指定root的方法更为常见。
