### ISSUE TITLE
No issues on updateing/lede-r6220-spi

### ISSUE THREAD

**Issue by emersion** [updateing/openwrt-r6220#6]
Hi,

Issues are disabled on https://github.com/updateing/lede-r6220-spi, can you enable them (you can do this in the repo settings).

Additionally, can you provide some instructions to flash LEDE?

Thanks!

**Comment by updateing** [comment]
1. Issues are disabled by default on a fork. I'll enable it later.
2. Will publish a guide for modded router later. But there are firmwares for stock NAND flash available on right.com.cn, you may be more interested in that...

**Comment by updateing** [comment]
Issues for LEDE enabled.

I'll just leave the flashing guide here:

(The hardware mods came from http://forum.anywlan.com/thread-380382-1-6.html)
1. Dump EEPROM data from stock ROM (the first 64KB of `Factory` partition)
1. Get an empty SPI flash chip (I'm using MX25L12835F) and write Breed for Newifi D1 to the beginning of the chip.
2. Remove NAND from PCB and solder the new SPI flash.
3. Move the resistor on R50 to R51, and the one on R48 to R46.
3. Power on the router, it should boot to Breed console automatically.
4. Go to http://192.168.1.1 and flash LEDE.
5. Reboot.
6. After booting, upload the EEPROM to /tmp and use `mtd-write` to write to `factory` partition.
7. Restore default settings in LEDE. After rebooting everything should be fine.

**Comment by emersion** [comment]
Thanks!
